=== Suhani0903/Capstone_Project-AIVS/src/test/resources/schemas/notes-schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "success": {
      "type": "boolean"
    },
    "status": {
      "type": "integer"
    },
    "message": {
      "type": "string"
    },
    "data": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string"
          },
          "title": {
            "type": "string"
          },
          "description": {
            "type": "string"
          },
          "category": {
            "type": "string"
          },
          "completed": {
            "type": "boolean"
          },
          "created_at": {
            "type": "string"
          },
          "updated_at": {
            "type": "string"
          },
          "user_id": {
            "type": "string"
          }
        },
        "required": [
          "id",
          "title",
          "description",
          "category",
          "completed",
          "created_at",
          "updated_at",
          "user_id"
        ]
      }
    }
  },
  "required": [
    "success",
    "status",
    "message",
    "data"
  ]
}

=== Suhani0903/Capstone_Project-AIVS/allure-report/data/attachments/fbfaba4c98107b.json
{
    "success": true,
    "status": 200,
    "message": "Notes successfully retrieved",
    "data": [
        {
            "id": "6a16aafb53916b0295cdc6e6",
            "title": "Test Note 2_142d360c",
            "description": "Description 2",
            "category": "Work",
            "completed": false,
            "created_at": "2026-05-27T08:27:39.453Z",
            "updated_at": "2026-05-27T08:27:39.453Z",
            "user_id": "6a149c7e0389350296654f50"
        }
    ]
}

=== Suhani0903/Capstone_Project-AIVS/allure-report/data/attachments/c5e240e8c5aa80cb.json
{
    "success": true,
    "status": 200,
    "message": "Notes successfully retrieved",
    "data": [
        {
            "id": "6a16aa9a53916b0295cdc67e",
            "title": "Test Note 1_0e6fc513",
            "description": "Description 1",
            "category": "Home",
            "completed": false,
            "created_at": "2026-05-27T08:26:02.499Z",
            "updated_at": "2026-05-27T08:26:02.499Z",
            "user_id": "6a1481510389350296653c20"
        },
        {
            "id": "6a16aa2053916b0295cdc5b5",
            "title": "TestNote_17b5f",
            "description": "This is test description",
            "category": "Home",
            "completed": false,
            "created_at": "2026-05-27T08:24:00.909Z",
            "updated_at": "2026-05-27T08:24:00.909Z",
            "user_id": "6a1481510389350296653c20"
        },
        {
            "id": "6a16a7b453916b0295cdc0e9",
            "title": "TestNote_57bff",
            "description": "This is test description",
            "category": "Home",
            "completed": false,
            "created_at": "2026-05-27T08:13:40.600Z",
            "updated_at": "2026-05-27T08:13:40.600Z",
            "user_id": "6a1481510389350296653c20"
        },
        {
            "id": "6a15688a53916b0295cd180c",
            "title": "Test Note 1_1779787857949",
            "description": "Description 1",
            "category": "Home",
            "completed": false,
            "created_at": "2026-05-26T09:31:54.986Z",
            "updated_at": "2026-05-26T09:31:54.986Z",
            "user_id": "6a1481510389350296653c20"
        },
        {
            "id": "6a155fca53916b0295cd0646",
            "title": "Test Note 1_a23d270f",
            "description": "Description 1",
            "category": "Home",
            "completed": false,
            "created_at": "2026-05-26T08:54:34.441Z",
            "updated_at": "2026-05-26T08:54:34.441Z",
            "user_id": "6a1481510389350296653c20"
        },
        {
            "id": "6a155f2753916b0295cd0566",
            "title": "Test Note 1_96f4636a",
            "description": "Description 1",
            "category": "Home",
            "completed": false,
            "created_at": "2026-05-26T08:51:51.210Z",
            "updated_at": "2026-05-26T08:51:51.210Z",
            "user_id": "6a1481510389350296653c20"
        },
        {
            "id": "6a153780038935029665dce7",
            "title": "Test Note 1_1779775249554",
            "description": "Description 1",
            "category": "Home",
            "completed": false,
            "created_at": "2026-05-26T06:02:40.018Z",
            "updated_at": "2026-05-26T06:02:40.018Z",
            "user_id": "6a1481510389350296653c20"
        },
        {
            "id": "6a15306a038935029665c3c5",
            "title": "Test Note 1_a626ba36",
            "description": "Description 1",
            "category": "Home",
            "completed": false,
            "created_at": "2026-05-26T05:32:26.419Z",
            "updated_at": "2026-05-26T05:32:26.419Z",
            "user_id": "6a1481510389350296653c20"
        }
    ]
}
